In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from torch.distributions import Multinomial

from torch.utils.data import DataLoader, Dataset

In [2]:
len({i: t for i, t in enumerate(torch.randn((10,3)))})

10

In [3]:
class simple(Dataset):
    def __init__(self):
        self.input_data = torch.randn((11, 5))
        self.target_values = torch.rand((11, 7))
#         self.input_data = {i: t for i, t in enumerate(torch.randn((11, 3)))}
#         self.cs = {i: t for i, t in enumerate(torch.rand((11, 5)))}
    
        print("\n-----\nmock data: {}\n\ntarget output: {}".format(self.input_data, self.target_values))

    
    def __len__(self):
        return len(self.input_data)
    
    def __getitem__(self, idx):
        return self.input_data[idx]
#         for each in self.input_data:
#             return each
    
#     def __iter__(self):
#         for k, v in self.ds:
#             print("----\nindex: {}\nvalue: {}\n".format(k, v))

In [4]:
sim = simple()

simple_dataload = DataLoader(sim, batch_size=2, shuffle=False)

for thing in simple_dataload:
    print(thing)

# for i, data, target in iter(simple_dataload):
#     print("\n------\nindexs: {}\nvalues: {}".format(i, data))


-----
mock data: tensor([[ 0.6345,  1.1267,  0.6607, -2.3244,  1.9640],
        [-1.6958,  0.8349, -0.1122,  0.2532, -0.2475],
        [ 0.2809,  0.2856, -0.3635,  0.8085,  0.8682],
        [-0.7592,  0.4873, -2.6690,  0.3352, -0.2978],
        [-0.7063,  1.2172, -0.4476, -0.6791,  1.9936],
        [ 0.8209, -0.0480, -0.6448,  0.1497, -0.1159],
        [-0.7147,  0.3699, -0.0973,  0.5046,  0.9169],
        [ 0.2818, -0.6481, -1.8644, -1.0849,  0.3173],
        [ 0.1218, -0.0676,  0.3210, -0.7297,  0.6859],
        [ 0.8857, -0.4955, -0.1660, -0.1517, -1.2053],
        [ 1.5045,  0.9623,  0.5579,  0.6380,  0.5878]])

target output: tensor([[0.7385, 0.5791, 0.6445, 0.6218, 0.2177, 0.4366, 0.5374],
        [0.3247, 0.4145, 0.8585, 0.1303, 0.1534, 0.5820, 0.8935],
        [0.2903, 0.2652, 0.3186, 0.0241, 0.9897, 0.2448, 0.5200],
        [0.8905, 0.7801, 0.1391, 0.8198, 0.9535, 0.0876, 0.7513],
        [0.9876, 0.1603, 0.5984, 0.2344, 0.0389, 0.3260, 0.3178],
        [0.3163, 0.1481, 0.481

In [5]:
torch.tensor([1., 1., 1.])

tensor([1., 1., 1.])

In [6]:
y = torch.rand((11, 3))

In [7]:
# probs = nn.Softmax(torch.rand((5, 11)))'

y = torch.rand((50, 3))

y = y * 1000
y = y.apply_(int)
print(y)
sample_probs = nn.Softmax(dim=1)(torch.rand((1, 3))).squeeze()
print("MAX:y.sum(-1).max())")
print(sample_probs)
print(sample_probs.sum())
idx = Multinomial(total_count=int(y.sum(-1).max()), probs=sample_probs).log_prob(y)
print(idx)


tensor([[ 63.,   0., 361.],
        [890., 878., 397.],
        [711., 723., 315.],
        [489., 702., 575.],
        [ 30., 435., 578.],
        [ 59., 218., 236.],
        [680., 732., 198.],
        [889., 638., 948.],
        [573., 610., 341.],
        [214., 478., 450.],
        [858., 750., 660.],
        [ 64., 532., 219.],
        [887., 736., 157.],
        [705., 525., 894.],
        [478., 837., 546.],
        [790.,  48., 306.],
        [347., 600., 361.],
        [210., 639., 753.],
        [844., 954., 261.],
        [611.,  45., 707.],
        [673.,   9., 207.],
        [827., 547., 965.],
        [670., 307., 852.],
        [413., 579., 167.],
        [463., 123., 423.],
        [993., 115.,  37.],
        [695., 362., 263.],
        [666., 772., 779.],
        [134., 947., 967.],
        [908., 236., 965.],
        [391., 310., 582.],
        [ 10., 560., 833.],
        [629., 344., 825.],
        [821., 522., 670.],
        [190., 462.,  46.],
        [714., 166.,

In [9]:
Multinomial(probs=torch.tensor([0.9977, 0.5481, 0.3348, 0.5036, 0.7178])).log_prob(torch.tensor([0.2450, 0.2137, 0.1361, 0.2050, 0.2001]))

tensor(-1.1941)

In [10]:
print(sim.target_values.T.size())

Multinomial(nn.Softmax(sim.target_values.T), 11).log_prob()

torch.Size([7, 11])


NotImplementedError: inhomogeneous total_count is not supported

In [11]:
class Smodel(nn.Module):
    def __init__(self):
        super().__init__()
        self.e = nn.Embedding(3, 6)
        self.d = nn.Sequential(
            nn.Linear(6, 5),
            nn.Softmax(dim=0)
        )
        
        #         batch_results = torch.tensor((len(samples), 3))

#         for i, sample in enumerate(samples):
#             target_idx = torch.randint(0, len(sample))
#             batch_results[i, 1] = target_idx
    def forward(self, sample_idxs, samples, target):
        
        z = self.e(target_idx)
        print(z)
        pred_y = self.d(z)
        lp = Multinomial(samples[sample_idxs, target_idx]).log_prob(pred_y).mean()
#         pred_y = self.d(z)
#         print("\n-----\nindexes: {}\npreds: {}\ntargets: {}".format(indxs, pred_y, targets))
        return batch_results

In [12]:
simple_model = Smodel()

a, b, c = iter(simple_dataload).next()
a = a.unsqueeze(1)
c[:, :, 3].mean()
# first_eval = simple_model(a, b, c)

ValueError: not enough values to unpack (expected 3, got 2)

In [13]:
torch.manual_seed(3)

alegra = nn.Embedding(6, 5)
bart = nn.Linear(5, 7)

print("the 'embedding' weights:\n{}".format(alegra.weight))


charlie = torch.tensor([1, 3]).unsqueeze(1)
print(charlie)

daniel = alegra(charlie)
print(daniel)

ethan = bart(daniel)
print(ethan)

# the 'correct' values
frank = torch.randn((6, 7))
print(frank)

the 'embedding' weights:
Parameter containing:
tensor([[-0.0766,  0.3599, -0.7820,  0.0715,  0.6648],
        [-0.2868,  1.6206, -1.5967, -0.0517, -0.3060],
        [ 0.2485, -0.2226,  0.9132,  0.2043, -0.0776],
        [-1.8054, -0.4760, -0.2929, -0.3481,  0.3487],
        [ 0.0371, -0.0677,  0.7737, -0.1092, -0.2712],
        [ 0.1416,  0.1295,  0.6814, -0.9583,  0.0639]], requires_grad=True)
tensor([[1],
        [3]])
tensor([[[-0.2868,  1.6206, -1.5967, -0.0517, -0.3060]],

        [[-1.8054, -0.4760, -0.2929, -0.3481,  0.3487]]],
       grad_fn=<EmbeddingBackward0>)
tensor([[[-0.4651, -1.1347,  0.2816,  0.2815, -1.3331, -0.3286,  0.1355]],

        [[ 0.1736, -0.2243,  0.2617,  0.5249, -0.3633, -0.4344, -0.9395]]],
       grad_fn=<AddBackward0>)
tensor([[ 0.3174,  0.1450, -0.6232, -0.0112, -0.3531, -0.8388, -1.2329],
        [-0.6806,  0.5161, -0.8823,  0.5617,  1.4444, -0.2090, -3.1117],
        [-0.4260,  1.3343,  0.6623,  0.6229,  0.4463,  0.7688,  1.5659],
        [ 0.5320, -1

In [14]:
gerry = torch.rand((5, 1))
isaac = torch.tensor([2])
print(isaac)
print(gerry)
print(alegra.weight)

harry = alegra(isaac) @ gerry

print(harry)

tensor([2])
tensor([[0.6227],
        [0.0157],
        [0.7459],
        [0.9833],
        [0.1442]])
Parameter containing:
tensor([[-0.0766,  0.3599, -0.7820,  0.0715,  0.6648],
        [-0.2868,  1.6206, -1.5967, -0.0517, -0.3060],
        [ 0.2485, -0.2226,  0.9132,  0.2043, -0.0776],
        [-1.8054, -0.4760, -0.2929, -0.3481,  0.3487],
        [ 0.0371, -0.0677,  0.7737, -0.1092, -0.2712],
        [ 0.1416,  0.1295,  0.6814, -0.9583,  0.0639]], requires_grad=True)
tensor([[1.0221]], grad_fn=<MmBackward0>)


In [15]:
for i, t in enumerate(charlie):
    

SyntaxError: unexpected EOF while parsing (1604479787.py, line 2)

In [16]:
rand_data = torch.randn(36, 1)

en = nn.Embedding(36, 5)
inds = torch.LongTensor([0, 1, 2])


en(inds)


tensor([[ 1.2386,  2.3908, -0.5404,  1.1440,  0.3812],
        [-1.8417, -0.5090, -0.4037,  1.9962, -0.2039],
        [-0.7219,  1.6073,  0.3807, -0.6203,  0.4096]],
       grad_fn=<EmbeddingBackward0>)

In [17]:
te = nn.Embedding(5, 3)

emidxs = torch.tensor([1, 2])

entire = list(te.parameters())

vanilla = te(emidxs)

fancy = te(emidxs).view((1, -1))

print("{}\n{}\n{}".format(entire, vanilla, fancy))

[Parameter containing:
tensor([[ 3.1515, -1.0525,  1.5625],
        [ 0.0747, -0.4966, -1.0815],
        [ 0.1141, -0.1095,  1.0366],
        [ 1.4308, -0.8927,  0.4165],
        [ 1.2339,  0.2398, -0.6728]], requires_grad=True)]
tensor([[ 0.0747, -0.4966, -1.0815],
        [ 0.1141, -0.1095,  1.0366]], grad_fn=<EmbeddingBackward0>)
tensor([[ 0.0747, -0.4966, -1.0815,  0.1141, -0.1095,  1.0366]],
       grad_fn=<ViewBackward0>)


In [18]:
CONTEXT_SIZE = 2
EMBEDDING_DIM = 10
# We will use Shakespeare Sonnet 2
test_sentence = """When forty winters shall besiege thy brow,
And dig deep trenches in thy beauty's field,
Thy youth's proud livery so gazed on now,
Will be a totter'd weed of small worth held:
Then being asked, where all thy beauty lies,
Where all the treasure of thy lusty days;
To say, within thine own deep sunken eyes,
Were an all-eating shame, and thriftless praise.
How much more praise deserv'd thy beauty's use,
If thou couldst answer 'This fair child of mine
Shall sum my count, and make my old excuse,'
Proving his beauty by succession thine!
This were to be new made when thou art old,
And see thy blood warm when thou feel'st it cold.""".split()
# we should tokenize the input, but we will ignore that for now
# build a list of tuples.
# Each tuple is ([ word_i-CONTEXT_SIZE, ..., word_i-1 ], target word)
ngrams = [
    (
        [test_sentence[i - j - 1] for j in range(CONTEXT_SIZE)],
        test_sentence[i]
    )
    for i in range(CONTEXT_SIZE, len(test_sentence))
]
# Print the first 3, just so you can see what they look like.
print(ngrams[:3])

[(['forty', 'When'], 'winters'), (['winters', 'forty'], 'shall'), (['shall', 'winters'], 'besiege')]


In [19]:
vocab = set(test_sentence)
word_to_ix = {word: i for i, word in enumerate(vocab)}

for context, target in ngrams:
    print("target: {}  |  context: {}".format(target, context))
    context_idxs = torch.tensor([word_to_ix[w] for w in context], dtype=torch.long)
    print(context_idxs)

target: winters  |  context: ['forty', 'When']
tensor([ 1, 40])
target: shall  |  context: ['winters', 'forty']
tensor([87,  1])
target: besiege  |  context: ['shall', 'winters']
tensor([27, 87])
target: thy  |  context: ['besiege', 'shall']
tensor([18, 27])
target: brow,  |  context: ['thy', 'besiege']
tensor([91, 18])
target: And  |  context: ['brow,', 'thy']
tensor([83, 91])
target: dig  |  context: ['And', 'brow,']
tensor([60, 83])
target: deep  |  context: ['dig', 'And']
tensor([61, 60])
target: trenches  |  context: ['deep', 'dig']
tensor([16, 61])
target: in  |  context: ['trenches', 'deep']
tensor([86, 16])
target: thy  |  context: ['in', 'trenches']
tensor([31, 86])
target: beauty's  |  context: ['thy', 'in']
tensor([91, 31])
target: field,  |  context: ["beauty's", 'thy']
tensor([ 0, 91])
target: Thy  |  context: ['field,', "beauty's"]
tensor([62,  0])
target: youth's  |  context: ['Thy', 'field,']
tensor([48, 62])
target: proud  |  context: ["youth's", 'Thy']
tensor([20, 48]

In [20]:
a = torch.randint(5, (1, 25))
b = torch.rand(25, 25)

print(a, "\n", b)
c = a * b
c.shape

tensor([[2, 1, 2, 0, 3, 0, 0, 0, 2, 1, 4, 0, 1, 2, 0, 2, 4, 4, 2, 4, 3, 2, 0, 4,
         2]]) 
 tensor([[0.4919, 0.4203, 0.2270, 0.5633, 0.8328, 0.8511, 0.3599, 0.0906, 0.2945,
         0.3817, 0.5843, 0.7241, 0.6673, 0.3415, 0.0420, 0.7143, 0.6089, 0.1226,
         0.5414, 0.0546, 0.1942, 0.7059, 0.7172, 0.8982, 0.1690],
        [0.4065, 0.5680, 0.8627, 0.7599, 0.5236, 0.8203, 0.4861, 0.0922, 0.7479,
         0.1131, 0.4924, 0.7504, 0.0550, 0.7544, 0.0147, 0.4415, 0.7593, 0.9569,
         0.7107, 0.6329, 0.7843, 0.3527, 0.6003, 0.3375, 0.1784],
        [0.9599, 0.0402, 0.2174, 0.5971, 0.4090, 0.5508, 0.1647, 0.1346, 0.0786,
         0.0070, 0.7698, 0.2942, 0.9401, 0.8595, 0.0551, 0.0698, 0.1540, 0.1370,
         0.9220, 0.4467, 0.8543, 0.5019, 0.6808, 0.1251, 0.0417],
        [0.9685, 0.0883, 0.9937, 0.1013, 0.9202, 0.4475, 0.5616, 0.4061, 0.9649,
         0.4942, 0.7478, 0.4272, 0.8939, 0.4524, 0.8595, 0.5594, 0.6286, 0.0110,
         0.5397, 0.0912, 0.2744, 0.2430, 0.9953, 0.1355, 

torch.Size([25, 25])

In [21]:
torch.tensor((torch.tensor(8), torch.tensor(3))).unsqueeze(1)

tensor([[8],
        [3]])

In [22]:
g = {}
g = { i: cnt.item() for i, cnt in enumerate(torch.tensor([0, 2, 3, 0, 5])) if cnt > 0}
# print(g, "\n")
# g[:, 0]
g

{1: 2, 2: 3, 4: 5}

In [93]:
unique = 3
cnt = 15

torch.randint(unique, (1, cnt)).unsqueeze(1)

tensor([[[1, 0, 0, 0, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2]]])

In [94]:
class rand_size(Dataset):
    def __init__(self):
        self.a = torch.tensor([[0, 1, 2, 0, 0],
                               [3, 0, 0, 1, 2]])
    
    def __len__(self):
        return len(self.a)
    
    def __getitem__(self, idx):
        return self.a[idx][self.a[idx] != 0].unsqueeze(1)

In [95]:
rs = rand_size()

In [96]:
rl = DataLoader(rs, batch_size=2)

In [97]:
next(iter(rl))


RuntimeError: stack expects each tensor to be equal size, but got [2, 1] at entry 0 and [3, 1] at entry 1

In [39]:
tb = torch.tensor([0, 3, 5, 2])

In [43]:
tb[tb != 0]

tensor([3, 5, 2])